#ifndef CONVERSATIONS_VERSION_H
#define CONVERSATIONS_VERSION_H

#define CONVERSATIONS_VERSION "@VERSION@"
#define CONVERSATIONS_BRANCH "@CONV_BRANCH@"
#define CONVERSATIONS_SEMVER "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_REVISION@"

#endif //CONVERSATIONS_VERSION_H
